# Generated by Django 4.2.5 on 2023-09-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fac_recog',
            old_name='image_path',
            new_name='group_image_path',
        ),
        migrations.AddField(
            model_name='fac_recog',
            name='target_image_path',
            field=models.CharField(default={'svdds'}, max_length=500),
            preserve_default=False,
        ),
    ]
