# Generated by Django 4.2.5 on 2023-09-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_api', '0002_rename_image_path_fac_recog_group_image_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacRecogGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_image_path', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FacRecogTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_image_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='fac_recog',
        ),
    ]
