# Generated by Django 4.2.5 on 2023-09-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_api', '0003_facrecoggroup_facrecogtarget_delete_fac_recog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facrecoggroup',
            name='group_image_path',
            field=models.JSONField(),
        ),
    ]
