# Generated by Django 4.2.5 on 2023-09-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_api', '0004_alter_facrecoggroup_group_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facrecoggroup',
            name='group_image_path',
            field=models.ImageField(upload_to='GroupImages/'),
        ),
        migrations.AlterField(
            model_name='facrecogtarget',
            name='target_image_path',
            field=models.ImageField(upload_to='TargetImage/'),
        ),
    ]
